---
version: '2'
services:
  plex:
    image: plexinc/pms-docker
    container_name: plex
    volumes:
      - /opt/appdata/plex:/config
      - /mnt/storage:/data
    network_mode: host
    restart: always
    environment:
      - PLEX_CLAIM="nope"
      - PUID=${PUID}
      - PGID=${PGID}
  nzbget:
    image: linuxserver/nzbget
    container_name: nzbget
    volumes:
      - /opt/appdata/nzbget/config:/config
      - /opt/downloads:/downloads
      - /mnt/disk1/downloads/complete:/downloads/complete
    ports:
      - 6789:6789
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
  sonarr:
    image: linuxserver/sonarr
    container_name: sonarr
    depends_on:
      - nzbget
    volumes:
      - /opt/appdata/sonarr:/config
      - /mnt/storage/tv:/tv
      - /mnt/disk1/downloads/complete/tv:/downloads
    ports:
      - 8989:8989
    links:
      - nzbget
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    nowshowing:
    image: ninthwalker/nowshowing
    container_name: nowshowing
    volumes:
      - /opt/appdata/nowshowing:/config
    ports:
      - 27024:6789
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ="Europe/London"
      - PLEX_SERVER_IP="192.168.1.2"
      - PLEX_USERNAME="nope"
      - PLEX_PASSWORD="nooooope"
      - SMTP_SERVER="smtp.gmail.com"
      - SMTP_PORT="587"
      - EMAIL_USERNAME="nope"
      - EMAIL_PASSWORD="nooooooope"
    restart: always
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    volumes:
      - /opt/appdata/radarr:/config
      - /mnt/storage/movies:/movies
      - /mnt/disk1/downloads/complete/movies:/downloads
    ports:
      - 7878:7878
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
    restart:
      always
