---
- name: verify if a reboot is required after upgrade
  stat: path=/var/run/reboot-required
  register: reboot_required

- name: reboot system
  shell: sleep 2 && shutdown -r now
  async: 1
  poll: 0
  ignore_errors: true
  become: true
  when: reboot_required.stat.exists

- name: wait for server to come back
  local_action:
    module: wait_for
      host={{ inventory_hostname }}
      state=started
      delay=5
      timeout=30
  when: reboot_required.stat.exists

# - name: reboot server if /var/run/reboot-required exists
#   command: shutdown -r now
#   args:
#     removes: /var/run/reboot-required
#   become: true

# - name: Wait for server to come back
#   local_action:
#     module: wait_for
#       host="{{ inventory_hostname }}"
#       state=started
#       delay=5
#       timeout=30