---
- name: Install NFS dependencies
  apt:
    name: nfs-common
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Install NFS dependencies
  yum:
    name: nfs-utils
    state: latest
    update_cache: yes
  become: true
  when: ansible_distribution == "CentOS"

- name: Add NFS shares to fstab
  mount:
    src: 10.30.50.201:/mnt
    name: /mnt/app-data
    fstype: nfs
    state: mounted
  become: true