- name: install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - aptitude
    - bash-completion
    - git
    - openssh-client
    - openssh-server
    - wget
    - vim
  tags:
    - packages

- name: ensure os is up to date
  apt:
    update_cache: yes
    upgrade: full
    cache_valid_time: 300
