---
- name: install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - aptitude
  tags:
    - packages
  become: true

- name: install packages
  apt: pkg={{ item }} state=latest
  with_items:
    - aptitude
    - bash-completion
    - curl
    - git
    - openssh-client
    - openssh-server
    - open-vm-tools
    - wget
    - vim
  tags:
    - packages
  become: true

- name: Upgrade distribtuion
  apt:
    upgrade: dist
    update_cache: yes
    cache_valid_time: 3600
  become: true
