---
- include: ubuntu.yml
  when: ansible_distribution == "Ubuntu"
  register: result

- include: centos.yml
  when: ansible_distribution == "CentOS"

- name: Add user to Docker group
  user:
    name: "{{user.name}}"
    groups: docker
    append: yes
  become: true

## Should already be enabled by default
# - name: Enable Docker service
#   systemd:
#     name: docker
#     state: started
#     enabled: yes
#   become: true

# - name: Start docker after network shares are mounted
#   lineinfile:
#     path: /lib/systemd/system/docker.socket
#     state: present
#     insertafter: '^\[Unit\]$'
#     line: "After={{ nfs_mount.unit_file }}.mount"
#   become: true

# Required for some Ansible modules
- name: Install docker-py
  pip:
    name: docker-py
  become: true

# - name: Reboot
#   shell: sleep 2 && reboot
#   async: 1
#   poll: 0
#   ignore_errors: true
#   become: truevagr
#   when: results|succeeded

# - name: Wait for server to come back
#   local_action:
#     module: wait_for
#       host="{{ inventory_hostname }}"
#       state=started
#       delay=5
#       timeout=30
#   when: results|succeeded