---

# Based on https://docs.docker.com/engine/installation/li sudo apt-key fingerprint 0EBFCD88nux/ubuntu/

- name: Install Docker dependencies
  apt:
    name: "{{item}}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true
  with_items:
    - apt-transport-https
    - ca-certificates
    - software-properties-common
    - python3-pip

- name: Add Docker GPG key
  apt_key:
    id: 0EBFCD88
    url: "https://download.docker.com/linux/ubuntu/gpg"
    state: present
  become: true

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ansible_distribution_release}} stable"
    state: present
  become: true

- name: Install Docker
  apt:
    name: docker-ce
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  become: true
